### ISSUE TITLE
Some datapoint.zip files don't contain everything

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BuildStock#106]
Including enduse_timeseries.csv file. Not sure if this is problem in `complete_localResults.rb`, or what...

@ejhw

**Comment by shorowit** [comment]
If files are too big, they don't get included in the zip. Could that be it? See https://github.com/NREL/OpenStudio-workflow-gem/blob/develop/lib/openstudio/workflow/adapters/output_adapter.rb#L90-L114

**Comment by joseph-robertson** [comment]
I will log any datapoint ids without enduse_timeseries.csv file during post-processing.

**Comment by joseph-robertson** [comment]
2b5b410
