### ISSUE TITLE
E+ measure for run period custom ranges

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BuildStock#108]
Create this so we can run simulations using AMY files with timestamps covering more than one calendar year.

**Comment by joseph-robertson** [comment]
OpenStudio requires that the DATA PERIODS header row doesn't have years, e.g., 12/31 to 12/31. But the `RunPeriod:CustomRange` EnergyPlus object requires years, e.g., 12/31/2011 to 12/31/2012. So this measure alters the weather file located at `../in.epw`.

**Comment by shorowit** [comment]
@joseph-robertson This is done?
