### ISSUE TITLE
docs vulnerability

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BuildStock#127]
![image](https://user-images.githubusercontent.com/5861765/33029723-93c1df1a-cdd6-11e7-969c-64a907b85f67.png)

**Comment by shorowit** [comment]
Probably not a big deal. Dismissed the warning.

**Comment by nmerket** [comment]
Yes, it is not a big deal. It only ever runs locally while someone is actively working on the docs. I _should_ fix it and probably will eventually, but it's certainly not a priority and poses no real security threat.
