### ISSUE TITLE
Clean up Heating Setpoint options in options_lookup.tsv

### ISSUE THREAD

**Issue by jmaguire1** [NREL/OpenStudio-BuildStock#140]
I noticed that there's a few heating setpoint options (63F w/ setback, 71F w/setback and 73F w/setback) that don't actually have any setback even though the name implies that they would. It might be worth seeing where these options are being used and deleting them if possible, they're identical to other existing options.

**Comment by shorowit** [comment]
It doesn't look like they are used. The ones that are used got updated in https://github.com/NREL/OpenStudio-BuildStock/commit/6aeb64a738777a47b915c8022d350c575decdc71#diff-7af024a2147fffc713953725c25f1519. I vote to delete them.

**Comment by jmaguire1** [comment]
Ok, I'll go ahead and do that, thanks for looking into it @shorowit
