### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by ejhw** [NREL/OpenStudio-BuildStock#149]
### Branch owners:
Please update status. Can we prune branches that we're no longer using?

| branch            | owner             | status |
|-------------------|-------------------|--------|
| draw_profile      | @jmaguire1        | ?      |
| hw-schedule-sizes | @jmaguire1        | ?      |
| install_qual      | @joseph-robertson | active |
| mlr-updates       | @joseph-robertson | ?      |
| multifamily_tests | @joseph-robertson | active |
| multifamily       | @joseph-robertson | active |
| spot_ventilation  | @jmaguire1        | ?      |
| testing_sfa_mf    | @shorowit         | active |
| update-measures   | @joseph-robertson | ?      |
| utilitybills      | @joseph-robertson | ?      |

**Comment by joseph-robertson** [comment]
I believe update-measures belongs to @shorowit.
