### ISSUE TITLE
add openstudio.rb file in windows:ruby installer setup

### ISSUE THREAD

**Issue by mpathak24** [NREL/OpenStudio-BuildStock#184]
Following steps are missing from the `https://github.com/NREL/OpenStudio-BuildStock/blob/master/docs/source/advanced_tutorial/installer_setup.rst`. Similar instructions are available on [OpenStudio's getting started](http://nrel.github.io/OpenStudio-user-documentation/getting_started/getting_started/) page but users who have not visited that web page find difficult to proceed further on the ResStock PAT project.  The steps are:
1. Create a text file with the following text inside (modify C:\openstudio-2.3.0 based on where your version of OpenStudio is installed):

`require 'C:\openstudio-2.3.0\Ruby\openstudio.rb'`

2. Save the file as `openstudio.rb` to C:\ruby-2.2.4-x64-mingw32\lib\ruby\site_ruby\openstudio.rb (or wherever you installed Ruby).

**Comment by shorowit** [comment]
You can point people to here: http://nrel.github.io/OpenStudio-user-documentation/getting_started/getting_started/#installation-steps -- "Optional - Install Ruby"

**Comment by mpathak24** [comment]
yup; that's also a good idea. We  can a line in the end of the windows installer guide.
