### ISSUE TITLE
Adam/Eric seeing "could not load openstudio" at end of integrity checks

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BuildStock#200]

**Comment by shorowit** [comment]
Yes, it requires the OpenStudio Ruby bindings as mentioned at:
https://resstock.readthedocs.io/en/latest/advanced_tutorial/installer_setup.html#windows-setup

**Comment by joseph-robertson** [comment]
Does this prevent the integrity checks from actually working?

**Comment by joseph-robertson** [comment]
And would there be a way to remove the "Wrote output file buildstock.csv" line?

**Comment by shorowit** [comment]
Some of the integrity checks are not run if you get this error.

**Comment by shorowit** [comment]
The sampling script writes that message. The integrity checks call the sampling script, which generates this message and writes the specified file, but then the integrity checks clean up after it and deletes the file.
