### ISSUE TITLE
365 days hardcoded in various places

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BuildStock#254]
Not sure what implications this has when running simulations using leap year AMY weather file.

**Comment by shorowit** [comment]
Seems like we should always be calling https://github.com/NREL/OpenStudio-BuildStock/blob/master/resources/measures/HPXMLtoOpenStudio/resources/unit_conversions.rb#L237 and https://github.com/NREL/OpenStudio-BuildStock/blob/master/resources/measures/HPXMLtoOpenStudio/resources/unit_conversions.rb#L248, and then update those values for leap years?
