### ISSUE TITLE
Option names aren't parsed as strings?

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BuildStock#299]
Matt Leach was running into a problem where his option name, e.g., `Option=4.50` was showing up in the sampled buildstock.csv as `4.5`. This was creating a problem with the options lookup which expects `4.50`.

@shorowit

**Comment by vtnate** [comment]
I have a hunch Matt could be creating `Option=4.50` in Excel and Excel is then truncating the trailing zero. If he creates the file in a text editor the issue might be resolved. I have had to edit a file with Sublime Text in the past to get around this issue.

**Comment by joseph-robertson** [comment]
@nmerket is going to fix this issue in https://github.com/NREL/buildstockbatch/issues/107.
