### ISSUE TITLE
Update occupant equations, refactor plug load equation to be function of occupants (not bedrooms)

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BuildStock#323]
@ejhw and I talked about this.

Based on RECS 2015 (instead of RECS 2001) we should try:

* updating equations in https://github.com/NREL/OpenStudio-BuildStock/blob/master/resources/measures/HPXMLtoOpenStudio/resources/geometry.rb#L1464-L1473 using RECS 2015 data

* updating the plug load equation in https://github.com/NREL/OpenStudio-BuildStock/blob/master/resources/measures/ResidentialMiscPlugLoads/measure.rb#L150 to be a function of occupants/ffa instead of beds/ffa

This also supports MF AEDG work.

**Comment by joseph-robertson** [comment]
**OCCUPANTS = f(BEDROOMS)**

![SFD_num_occupants](https://user-images.githubusercontent.com/8516790/65637146-eae2bc00-dfa0-11e9-9a1f-5a3661f28814.png)
![MF_num_occupants](https://user-images.githubusercontent.com/8516790/65637232-11a0f280-dfa1-11e9-83ee-9d4149b7b60a.png)

**Comment by joseph-robertson** [comment]
**PLUG LOAD ANNUAL KWH = f(OCCUPANTS, FINISHED FLOOR AREA)**

![SFD_mel_ann](https://user-images.githubusercontent.com/8516790/65637318-34cba200-dfa1-11e9-8447-a93b2762e3d6.png)

![MF_mel_ann](https://user-images.githubusercontent.com/8516790/65637350-401ecd80-dfa1-11e9-86e4-3e0d656051f0.png)

**Comment by shorowit** [comment]
@joseph-robertson This is done?
