### ISSUE TITLE
Adjust timeseries csv index for DST

### ISSUE THREAD

**Issue by aspeake** [NREL/OpenStudio-BuildStock#344]
The `TimeseriesCSVExport` measure outputs time at a constant interval across a year, regardless of time changes for daylight savings time. This can cause confusion, as E+ shifts schedules to account for DST, but our time output does not line up with this shift.

I propose having two columns for time:
1) Datetime index, that accounts for DST. This would skip the 2:00am hour at the start of DST, and have two 2:00 am hours at the end of DST
2) Interval index, a continuous integer index based on the reporting frequency (eg, `1..8760` for hourly)

**Comment by joseph-robertson** [comment]
@aspeake Wouldn't it be two 1:00am hours at the end of DST?

**Comment by joseph-robertson** [comment]
@aspeake Wouldn't it be two 1:00am hours at the end of DST?

**Comment by joseph-robertson** [comment]
Also, we should confirm that EnergyPlus applies the schedule shift at 2 AM. I would imagine that it happens at 12 AM. Perhaps you can determine this based on the setpoint schedules?

**Comment by jmaguire1** [comment]
I'm pretty sure it happens at midnight in E+, not 2 AM, but I could be wrong.

As a side note, it seems like we spend a lot of time dealing with DST for very little benefit, I can think of 3-4 times it's messed up some sort of comparison or output reporting off the top of my head...

**Comment by aspeake** [comment]
I ran a sim with a 24-hr TSP schedule and it does appear that it gets shifted at midnight, not at 2am.

**Comment by joseph-robertson** [comment]
So would it be:
* Start: ..., 10 PM, 11 PM, 1 AM, 2 AM, ...?
* End: ..., 10 PM, 11 PM, 11 PM, 12 AM, ...?

**Comment by aspeake** [comment]
Yes I believe so

**Comment by joseph-robertson** [comment]
Closed in #346.
