### ISSUE TITLE
Fix pool pump probabilities

### ISSUE THREAD

**Issue by ejhw** [NREL/OpenStudio-BuildStock#386]
In this commit, we accidentally changed pool pump probability to 100%. It should instead be whatever fraction/multiplier was previously being used for the National Average pool pump option. 
https://github.com/NREL/OpenStudio-BuildStock/commit/69a35b988fe6d7200c5b0fa0b76d8980a894805c#commitcomment-37116887

Pool heater probabilities look to be correct, though there may be opportunities for improvement:

 - Consider making gas pool heating dependent on Heating Fuel
 - Consider making pool pumps and pool heaters depend on region/climate zone based on RECS data

cc @afontani @ekpresent

**Comment by joseph-robertson** [comment]
Should SFA or MF buildings ever have pools?

**Comment by afontani** [comment]
@joseph-robertson: For Los Angeles, we did not model multifamily/SFA pools.  Since we are going toward a single unit representation, I would say no we should not model MF and SFA units with pools. As we get better with common spaces, I would include them there.

**Comment by ejhw** [comment]
In RECS, SFA homes can have pools.

**Comment by JLReyna** [comment]
In reality, SFA can have either shared pools (in common areas) or individual pools. @ejhw do you know if RECS reports common area pools or just individual pools? It's not obvious from the codebook. If available, I would vote we add in SFA individual pools, but not common area pools

**Comment by ejhw** [comment]
@JLReyna Looks like individual pools only:
![image](https://user-images.githubusercontent.com/1276021/73860886-7b57c580-47f9-11ea-8807-c3ca66211a14.png)
