### ISSUE TITLE
Remove redundant enduses

### ISSUE THREAD

**Issue by rajeee** [NREL/OpenStudio-BuildStock#403]
The internal_equipment_kwh enduse includes the other enduses and it creates double counting error when people sum all the enduses.
Suggestion is to remove from both results.csv and timeseries the "net_site_electricity_kwh" and "internal_equipment_kwh" so that we only have all the individual enduses which will sum up to the "total_site_electricity_kwh".

Along with this also remove the include_enduse_subcategories option from the simulation_output measure, and include all those subcategories by default.

This should get rid of lot of confusions and errors.

**Comment by joseph-robertson** [comment]
Remove include_enduse_subcategories from both the simulation output and timeseries measures. This will also require changes on the buildstockbatch side.
