### ISSUE TITLE
Geometry Unit Stories SF and Geometry Unit Stories MF are not used

### ISSUE THREAD

**Issue by ejhw** [NREL/OpenStudio-BuildStock#415]
Remove them?

From `options_lookup.tsv`:
Geometry Unit Stories SF	N/a																																														
Geometry Unit Stories SF	1																																														
Geometry Unit Stories SF	2																																														
Geometry Unit Stories SF	3																																														
Geometry Unit Stories SF	4+																																														
Geometry Unit Stories MF	N/a																																														
Geometry Unit Stories MF	1																																														
Geometry Unit Stories MF	2																																														
Geometry Unit Stories MF	3

cc @joseph-robertson @aspeake @vtnate

**Comment by shorowit** [comment]
@afontani This is done?

**Comment by afontani** [comment]
Yes. It is.  Addressed as part of PR #416. I will close it.
