### ISSUE TITLE
All analyses fails, even on tutorial

### ISSUE THREAD

**Issue by Sustainabilist** [NREL/OpenStudio-BuildStock#421]
When running the tutorial analysis, all datapoints fail consistently. 

![image](https://user-images.githubusercontent.com/4141291/76171948-07893f80-614e-11ea-9c11-d59de9f15038.png)

Steps I have taken to resolve the issue: 

- Simplifying the simulation to one measure

- Attempted to simulate other measures, such as ASHP measures

- Reviewing tutorial settings

- Replacing entire directory with downloaded zip of release 2.2.2 

Despite every step, including replacing the whole directory, the entire workflow fails consistently. I have attached the log files - one from the the analysis workflow and one from a worker. 

[analysis_log.txt](https://github.com/NREL/OpenStudio-BuildStock/files/4303958/analysis_log.txt)
[worker_log.txt](https://github.com/NREL/OpenStudio-BuildStock/files/4303959/worker_log.txt)

**Comment by joseph-robertson** [comment]
@Sustainabilist, looks like the download of your weather zip is failing; the s3 bucket containing this file has recently been switched to block public access. I will soon work on releasing a 2.2.3 patch containing a working weather url.

**Comment by joseph-robertson** [comment]
Here is the link to the 2.2.3 patch: https://github.com/NREL/OpenStudio-BuildStock/releases/tag/v2.2.3

@Sustainabilist

**Comment by shorowit** [comment]
Closing. Please re-open this issue if the new version doesn't fix it.
