### ISSUE TITLE
Specify key value in timeseries outputs

### ISSUE THREAD

**Issue by aspeake** [NREL/OpenStudio-BuildStock#435]
For surface variables, enable the `TimeseriesCSVExport` measure to output specific surfaces, instead of the default all (`*`).

**Comment by joseph-robertson** [comment]
Perhaps you can generalize this. For example, add ability to report output variables for specific surfaces, specific thermal zones, etc.

**Comment by aspeake** [comment]
> 
> 
> Perhaps you can generalize this. For example, add ability to report output variables for specific surfaces, specific thermal zones, etc.

Looking at the measure more closely, this feature will end up being more general than just outputting surface, instead you will specify a key value, which can be a surface, equipment, zone, etc.
