### ISSUE TITLE
Missing Argument when No HVAC System is Assigned

### ISSUE THREAD

**Issue by aspeake** [NREL/OpenStudio-BuildStock#440]
Possibly related to #434

When running homes with no HVAC system in ResStock, the simulation fails with this error:
`Required argument 'has_hvac_flue' not provided for measure 'ResidentialAirflow'.`

This is because `has_hvac_flue` is only specified in `HVAC System *` parameters when the option is not `None`.  With the current sampling routine, there is a subset of SFD, SFA, and MF homes that do not have any heating or cooling systems.

_Suggested Fix:_
I don't believe just setting `has_hvac_flue == False` for all `None` options will work in case this overwrites a `True` value specified for another HVAC System. Further discussion is needed to determine the best path forward

**Comment by joseph-robertson** [comment]
@aspeake What would be a scenario where if we used `Heating Fuel=None` and `Heating Fuel=Other Fuel` to set `has_hvac_flue=false`, further downstream it would be overwritten to `has_hvac_flue=true`?
