### ISSUE TITLE
Utility bill calculations

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BuildStock#46]
Use hourly output timeseries data and SAM SDK for utility bill calculations.

- [x] Reporting measure for creating hourly output csv
- [x] Be able to `require ffi`
    - Right now `ffi` is not packaged with openstudio; however, can run unit tests.
- [x] Call `utilityrate3` SAM module with appropriate inputs
  - Inputs from api calls to openei urdb
- [x] Register the calculated energy, demand, and utility bill values somewhere

**Comment by joseph-robertson** [comment]
Received an example file, rescom.rb, from Rob Eger which demonstrates use of annualoutput, utilityrate2, cashloan modules.

**Comment by joseph-robertson** [comment]
API key is an argument to the utility bill measure
We can require that the user supply it, although they may run into throttling issues
Other possible solutions:
- A
  - Upload full set of "UtilityID_RateID" json files to S3
  - Pull applicable json files from S3 using worker init script (similar to weather files)
- B
  - Make API calls but cache results
  - Call cached results if they exist

**Comment by ejhw** [comment]
Decision: C) Include full set of json files in PAT projects

Also add measure arguments to allow custom elec, gas, propane, and fuel oil rates that overwrite any jsons and resource files. ($/unit and $ fixed for elec and gas; $/unit only for propane and fuel oil).

**Comment by shorowit** [comment]
I think some changes are needed. The two major problems I see are:
1. If you enable the utility bill measure without enabling the timeseries measure, you get failed datapoints. It'd be better if you got simulation results, just without utility bill results.
2. You shouldn't have to enable the timeseries measure to get utility bill results. A user would never expect this.

My recommendation: The utility bill measure should automatically request the fuel consumption outputs that it needs. If both the timeseries measure and utility bill measure are enabled, they would be smart enough not to request the same outputs from E+.

**Comment by joseph-robertson** [comment]
Decision:
- [ ] if someone uses timeseries measure by itself -> get timeseries data for fuels and enduses
- [ ] if someone uses utility bill measure by itself -> get sqlfile timeseries data for fuels only -> utility bill calculation
- [ ] if someone uses both measures -> timeseries measure gets timeseries data for fuels and enduses, and utility bill measure gets sqlfile timeseries data for fuels only -> utility bill calculation

@shorowit

**Comment by joseph-robertson** [comment]
Still needs to be merged into master in the OpenStudio-BEopt repo.

**Comment by ejhw** [comment]
- [ ] Boolean argument for averaging across multiple rates within one EIA ID
- [ ] Write out table of average and standard deviations of annual bills for each rate_id (i.e., across all archetype ids); will be useful for filtering list of 4000 rates
- [ ] Filter list of 4000 rates (URDB team?)
@joseph-robertson

**Comment by ejhw** [comment]
> SAM makes other assumptions about time that may affect your analysis:
> 
> 1. It assumes that January 1 is a Monday, which will affect simulations involving weekday and weekend schedules (electricity rate structures, time-of-delivery price factors, etc.)
> 
> 2. It does not adjust for daylight savings time.
1. I think we can work around the first limitation by shifting days because Jan and Dec so that the timeseries we pass to SAM starts on a Monday. Not a high priority fix though.
2. In the real world, TOU periods are in clock time. E+ output timestamps are in local standard time, so I think we're fine.
cc @shorowit @joseph-robertson
