### ISSUE TITLE
Appliance design levels fluctuate between runs

### ISSUE THREAD

**Issue by aspeake** [NREL/OpenStudio-BuildStock#476]
When running the `example_single_family_detached_TMY.osw` file locally, the design levels for several appliances in the idfs change from run to run, even though nothing is changed in the code or input file. This appears to be changing the overall energy uses between runs. 

I am seeing a similar outcome in the idfs when running two different Eagle runs using the same `buildstock.csv`. 

**IDF comparison:**
![IDF Comparison](https://user-images.githubusercontent.com/44212066/90063221-4778c380-dca6-11ea-9426-80b34a2d7f7f.png)

**Comment by joseph-robertson** [comment]
Closed in #477.
