### ISSUE TITLE
Garage zone infiltration not always added to model

### ISSUE THREAD

**Issue by aspeake** [NREL/OpenStudio-BuildStock#479]
For 1-story, SFD homes with protruding garages, we expect an effective leakage area object added to the model for the garage and garage attic spaces, as shown below. However, these only get added about half of the time. 

In `airflow.rb` ([L46](https://github.com/NREL/OpenStudio-BuildStock/blob/master/resources/measures/HPXMLtoOpenStudio/resources/airflow.rb#L46)), the garage zone is only sometimes recognized as an OS garage zone type.

```
OS:SpaceInfiltration:EffectiveLeakageArea,
  {eff441dc-8b8e-4750-8438-7bd3ccd48c03}, !- Handle
  res infil|garage space,                 !- Name
  {1fc6b4d0-077e-466a-9cf5-a8abb3d20fac}, !- Space or SpaceType Name
  {ca87e77b-1253-4b28-a8e2-c049b33ab4f1}, !- Schedule Name
  484.901223413343,                       !- Effective Air Leakage Area {cm2}
  0.000242001550515464,                   !- Stack Coefficient
  5.99869313304048e-005;                  !- Wind Coefficient

OS:SpaceInfiltration:EffectiveLeakageArea,
  {b43e3071-a0a4-4373-9a7b-79fc2b24ec6f}, !- Handle
  res infil|garage attic space,           !- Name
  {f7c1e8eb-48a6-49cb-8c00-161d416524dd}, !- Space or SpaceType Name
  {ca87e77b-1253-4b28-a8e2-c049b33ab4f1}, !- Schedule Name
  484.901223413343,                       !- Effective Air Leakage Area {cm2}
  0.000242001550515464,                   !- Stack Coefficient
  5.99869313304048e-005;                  !- Wind Coefficient
```

**Comment by aspeake** [comment]
The source of the issue is due to assigning two different standard space types to the same thermal zone. When there is a protruding garage, there is a garage attic space (space type = `garage attic`) and a garage space (space type = `garage`), both of which get assigned to the garage zone. When `Geometry.is_garage(garage_zone)` gets called ([here](https://github.com/NREL/OpenStudio-BuildStock/blob/master/resources/measures/HPXMLtoOpenStudio/resources/geometry.rb#L859)), it checks the space type of whatever space gets output first in the iteration.

@joseph-robertson @shorowit Should we assign the garage attic space to a `garage` space type and keep it part of the garage zone, or assign it an `unfinished attic` space type and include it in the attic zone? I think either of the solutions fix this problem.

Another option would be to alter the methods in `Geometry.rb` to check all spaces in a zone instead of just one.

**Comment by joseph-robertson** [comment]
I recall there being a reason to keep the garage attic separate from either the garage or unfinished attic, but I don't remember the reason.
