### ISSUE TITLE
Script to collect hourly output on server

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BuildStock#48]
- [x] zip
- [x] pandas hdf5
  - datapoint_id | Time | enduse_id | value
  - length of table is datapoint_ids * 8,760 * enduse_ids
  - convert string timestamps to epoch time?
- [x] h5py hdf5
  - store numpy arrays in format of original csv
  - store column names in `attrs`
  - convert string timestamps to epoch time?

@nmerket to review /resources/collect.py.

**Comment by joseph-robertson** [comment]
@ejhw,

Unzip [data_points.zip](https://github.com/NREL/OpenStudio-ResStock/files/910670/data_points.zip) (sample data) and place the h5 file in the resources directory. Then run

`python collect.py --function='read'`

to view the contents.

**Comment by ejhw** [comment]
@joseph-robertson, we can also explore making a script to put into this format: https://github.nrel.gov/dsgrid/dataformat. Contact Elaine if you need access.

**Comment by joseph-robertson** [comment]
I'm currently get the datapoint id by regex on the run.log. This id links each datapoints' time series data to building characteristics found in the output csv.
