### ISSUE TITLE
National-scale output scatter plots

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BuildStock#51]
Measured consumption from RECS.

- [x] Are they weather-normalized values?

**Comment by ejhw** [comment]
> Are they normalized values?
@joseph-robertson Is that a question for me? How would they be normalized?

Can we make a scatter plot for FPL bins (this would require some post-processing to apply the inverse tsv)?

And we should make some CDF or KDE comparisons for slices as well.

**Comment by joseph-robertson** [comment]
@ejhw By normalized, I mean weather normalized.

Let's touch base on:
- [ ] Scatter plot for FPL bins
- [ ] CDF or KDE comparisons for slices

**Comment by ejhw** [comment]
No, I don't think RECS consumption values are weather-normalized—I forget if we did that for the previous calibration. The HDD and CDD for 2009 and normals are reported in each row, so that should be pretty easy.

**Comment by ejhw** [comment]
@joseph-robertson Can you implement weather normalization if not already done?

**Comment by joseph-robertson** [comment]
```
  df = df[df['hdd65']>0]
  df = df[df['cdd65']>0]

  # electricity
  df['kwhsph_nrm'] = df['kwhsph'] * ( df['hdd30yr'] / df['hdd65'] )
  df['kwhcol_nrm'] = df['kwhcol'] * ( df['cdd30yr'] / df['cdd65'] )
  df['kwhel_nrm'] = df['kwhsph_nrm'] + df['kwhcol_nrm'] + df['kwhwth'] + df['kwhrfg'] + df['kwhoth']
  
  # natural gas
  df['btungsph_nrm'] = df['btungsph'] * ( df['hdd30yr'] / df['hdd65'] )
  df['btung_nrm'] = df['btungsph_nrm'] + df['btungwth'] + df['btungoth']
  
  # propane
  df['btulpsph_nrm'] = df['btulpsph'] * ( df['hdd30yr'] / df['hdd65'] )
  df['btulp_nrm'] = df['btulpsph_nrm'] + df['btulpwth'] + df['btulpoth']
  
  # fuel oil
  df['btufosph_nrm'] = df['btufosph'] * ( df['hdd30yr'] / df['hdd65'] )
  df['btufo_nrm'] = df['btufosph_nrm'] + df['btufowth'] + df['btufooth']
  
  df['btuoth_nrm'] = df['btulp_nrm'] + df['btufo_nrm']
```

@ejhw
