### ISSUE TITLE
Add tsv option bin fracs using post-processing

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BuildStock#55]
- [x] Join `resstock_national.csv` output csv with tsv on its dependencies (default tsv=Federal Poverty Level). 
- [x] Multiply each option bin (frac) by the weight of houses that each simulation represents.
  - Using pandas `melt` function for this.
- [ ] Investigate how to avoid memory issues for large output csv files.
  - Tried approach of parallelizing hdf5 file writes for chunks.
- [ ] Use postgres and relational tables instead of trying to melt the entire csv.

**Comment by joseph-robertson** [comment]
Used pandas `melt` function for this.

**Comment by shorowit** [comment]
Is this still relevant?
