### ISSUE TITLE
national tsv file TODOs

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BuildStock#61]
- Federal Poverty Level (dependencies: Location MSA CD, Vintage, Geometry House Size, HVAC System Cooling Type
  - [ ] Complete Location MSA CD
- Geometry House Size (dependencies: Location Census Division, Vintage)
  - [ ] Use Location Census Division?
- HVAC System Cooling Type (dependencies: HVAC System Cooling)
  - [ ] Review
- Location Census Division (dependencies: Location EPW)
  - [ ] Should this include MSA?
- Location MSA CD (dependencies: Location Census Tract)
  - [ ] Complete this tsv
- Location Census Tract (dependencies: Location EPW, Vintage, Heating Fuel)
  - [ ] Complete this tsv

**Comment by ejhw** [comment]
Partially superseded by #66.
Review TSVs and remove those no longer needed
