### ISSUE TITLE
CO2e and source-site factors applied by eGRID subregion

### ISSUE THREAD

**Issue by ejhw** [NREL/OpenStudio-BuildStock#65]
Here’s the data file for mapping egrid_subregion to lb/MWh CO2e: https://www.epa.gov/sites/production/files/2017-02/egrid2014_data_v2.xlsx

from: https://www.epa.gov/energy/emissions-generation-resource-integrated-database-egrid (edited)

Worksheet: SRL14

Column CR:  eGRID subregion annual CO2e non-baseload output emission rate (lb/MWh) (SRNBC2ER)

**Comment by joseph-robertson** [comment]
Script to parse spreadsheet and produce csv of three columns:
- [ ] egrid region
- [ ] CO2e non-baseload output emission rate
- [ ] source-site factor (J2e)

**Comment by joseph-robertson** [comment]
https://github.nrel.gov/jrobert1/buildstockdb/commits/master

**Comment by ejhw** [comment]
@shorowit @nmerket @rHorsey Thoughts on merging that "buildstockdb" repo into the "OpenStudio-BuildStock" repo?

**Comment by joseph-robertson** [comment]
@ejhw I originally branched it off of the "OpenStudio-BuildStock" repo per @nmerket's suggestion of making it a python package.

**Comment by ejhw** [comment]
Oh yeah, forgot about that :)

**Comment by nmerket** [comment]
Yep. Please don't merge them.

**Comment by ejhw** [comment]
Done. Outstanding issue: https://github.nrel.gov/jrobert1/buildstockdb/issues/6
