### ISSUE TITLE
Area Median Income

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-BuildStock#66]
- [x] Derive TSVs from LMI Templates (https://drive.google.com/drive/folders/0B-LAKa-xpXo_dk5QaWNsTUo3VDA)
- [x] Modify StockPot db post-processing scripts to assign census tract, FPL, etc.

![img_0071](https://user-images.githubusercontent.com/8516790/29147343-9e9be61e-7d23-11e7-8849-624068c98247.JPG)

**Comment by joseph-robertson** [comment]
https://github.nrel.gov/jrobert1/buildstockdb/commit/f042a121ceacd384633dd4e7ee4d7829e2eb4af3

**Comment by ejhw** [comment]
@ejhw to review
