### ISSUE TITLE
Upgrade testing

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BuildStock#68]
Most testing has been focused on the existing housing stock. We need to do some testing of various types of upgrades. 

In particular, I'm concerned about upgrades that currently require multiple measures to be used but may not be obvious to the user. Many of the situations can probably be streamlined by either 1) making improvements to our measures or 2) reorganizing tsv's and/or option mapping as needed.

Some areas to look into:
- [x] Window Areas -> Constructions
- [x] Window Areas -> Overhangs
- [x] Door Areas -> Constructions
- [x] Water Heater -> HW Fixtures/CW/DW, Distribution, ...
- [x] Water Heater -> Solar Hot Water
- [x] Hot Water Fixtures -> Distribution
- [x] HVAC -> Setpoints
- [x] HVAC -> Ducts (tsv workaround)
- [x] HVAC -> Sizing
- [x] HVAC ->Dehumidifier
- [x] Cooling Setpoint -> Ceiling Fan (tsv workaround)
- [x] Clothes Washer -> Clothes Dryer

cc @ejhw

**Comment by joseph-robertson** [comment]
Unit tests for the ApplyUpgrade measure?

**Comment by shorowit** [comment]
That's not the issue, the ApplyUpgrade measure is performing properly. It's specific to our residential measures/workflow that it's calling. I am going to open some new tickets based on my testing, you'll see what I mean.

**Comment by shorowit** [comment]
First issue: https://github.com/NREL/OpenStudio-BEopt/issues/168

**Comment by shorowit** [comment]
Temporary workaround: https://github.com/NREL/OpenStudio-BuildStock/commit/eaf521e08be9178979d0146b17e772cd1180e773

**Comment by ejhw** [comment]
cc @trynthink
