### ISSUE TITLE
Invalid geometries

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BuildStock#77]
It's possible to create invalid geometry inputs (e.g., huge garage for a house with a small footprint). It affects the comed project and presumably some others.

Here's the specific situation that caused an error:
```
Calling ResidentialGeometrySingleFamilyDetached measure with arguments:
foundation_type -> unfinished basement
foundation_height -> 8
num_floors -> 2
garage_width -> 36
garage_depth -> 24
garage_protrusion -> 0.5
garage_pos -> Right
total_ffa -> 1000
living_height -> 8
aspect_ratio -> 1.8
attic_type -> unfinished attic
roof_type -> gable
roof_pitch -> 6:12
[16:05:07.139913 ERROR] Invalid living space and garage dimensions. 
```

**Comment by ejhw** [comment]
@joseph-robertson Can you please test the OS measure to see if it breaks for a 1000 sf 2 story house with a 2 car (24' x 24') garage? The above was a 3 car garage. Then we'll want to modify the RECS query script move 3-car 1000 sf probablities into the 1-car or 2-car bins.

**Comment by joseph-robertson** [comment]
@ejhw, it does not break when I change garage width from 36 to 24. So you want me to move probabilities for Option=3 Car into Option=2 Car for Geometry House Size=0-1499? For all projects or just comed?

**Comment by ejhw** [comment]
@joseph-robertson Can you make the change in the RECS query script and then distribute the new Geometry Garage.tsv to all ResStock projects?

**Comment by shorowit** [comment]
Not the Testing or PNW projects.

**Comment by joseph-robertson** [comment]
Yes. With the exception of the pnw project since it queries its own data? Any other exceptions?

**Comment by joseph-robertson** [comment]
Oops. Didn't hit refresh. Got it.
