### ISSUE TITLE
Additional timeseries output variables

### ISSUE THREAD

**Issue by ejhw** [NREL/OpenStudio-BuildStock#82]
Dane would like us to send him some sample timeseries output (10 minutely, individual home) when convenient. He's interested in some additional output variables. Can we add options to include the following output variables to our time series measure?

- temperatures (living space only okay)
- RH
- Run time fraction of HVAC equipment

**Comment by joseph-robertson** [comment]
Do you want timeseries output for this individual home using the ResStock framework? Maybe this makes more sense just running one osw from the OpenStudio-BEopt repo.

**Comment by ejhw** [comment]
Eventually, Dane will want these outputs for hundreds or thousands of homes. This is for training machine learning models for the foresee project.

**Comment by joseph-robertson** [comment]
OK. I'll create a branch on the OpenStudio-BEopt repo with changes to the timeseries measure. And then I'll create a branch on this repo with a "foresee" resstock project that incorporates the changed timeseries measure.

**Comment by ejhw** [comment]
We should make the three outputs mentioned above optional, since they aren't important for all applications. We'll also need to decide how to deal with them if aggregating up individual home data (e.g., do we average the temperatures, or just throw them out if aggregating?).

**Comment by shorowit** [comment]
A user might be able to add one of the existing [BCL reporting measures](https://bcl.nrel.gov/search/site?f[0]=im_field_measure_tags%3A959) to specify these outputs.

There could be limitations where a user doesn't know the name of a zone they want, e.g., temperatures for, so they'd have to use `*` and request temperatures for all zones. But that should be fine.
