### ISSUE TITLE
Remove unused TSVs

### ISSUE THREAD

**Issue by ejhw** [NREL/OpenStudio-BuildStock#88]

**Comment by ejhw** [comment]
- https://github.com/NREL/OpenStudio-BuildStock/blob/master/project_resstock_national/housing_characteristics/Location%20MSA%20CD.tsv ?
- https://github.com/NREL/OpenStudio-BuildStock/blob/master/project_resstock_national/housing_characteristics/Location%20Census%20Division.tsv ?
- https://github.com/NREL/OpenStudio-BuildStock/blob/master/project_resstock_national/housing_characteristics/Location%20IECC%20EPW.tsv ?
- https://raw.githubusercontent.com/NREL/OpenStudio-BuildStock/master/project_resstock_national/housing_characteristics/Location%20Census%20Tract.tsv ?

**Comment by joseph-robertson** [comment]
One example of how Location Census Division is used: 

Federal Poverty Level.tsv has dependencies of:
- Location Census Division
- Vintage
- Geometry House Size
- HVAC System Cooling Type

Federal Poverty Level is not sampled and assigned to buildstock.csv. Instead, sets of fractions for each row of Federal Poverty Level.tsv are assigned to each datapoint post simulation. This requires that the results csv have a building_characteristics_report.location_census_division column sampled pre simulation.

Maybe we can get rid of the other three tsv files you mention above though- I think they were experimental or something.

@ejhw

**Comment by ejhw** [comment]
Federal Poverty Level.tsv will be going away and replaced with the AMI and FPL tables that have census tract resolution.

**Comment by joseph-robertson** [comment]
These are removed on master as well as multifamily.

**Comment by shorowit** [comment]
This can be closed?
