### ISSUE TITLE
Update rakefile

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-BuildStock#96]
Update copy_beopt_files rake task in both OpenStudio-BuildStock and OpenStudio-ERI repos to grab the files directly from GitHub. Look for `# TODO: Should really grab latest from https://github.com/NREL/OpenStudio-BEopt/archive/master.zip`

**Comment by joseph-robertson** [comment]
- [ ] Not sure how to delete measure.zip (has to be unlinked first or something?)
